{{- if and (not (or .Values.global.openshift $.Values.global.openshift)) .Values.ingress.enabled }}
# Control Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trustgate-admin
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: control-plane
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.controlPlane.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trustgate-control-plane
                port:
                  number: {{ .Values.controlPlane.ports.http }}
---
# Data Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trustgate-gateway
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: data-plane
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.dataPlane.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trustgate-data-plane
                port:
                  number: {{ .Values.dataPlane.ports.http }}

---
# Actions Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trustgate-actions
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: actions
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.actions.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trustgate-actions
                port:
                  number: {{ .Values.actions.ports.http }}
{{- end }}