{{- if .Values.dataPlane }}
  {{- if .Values.dataPlane.components }}
    {{- if .Values.dataPlane.components.api }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-plane-trusttest-config
  labels:
    app: api
    plane: data
data:
  .trusttest_config.json: |-
{{ .Files.Get "files/.trusttest_config.json" | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }} 