{{- if .Values.dataPlane }}
  {{- if .Values.dataPlane.components }}
    {{- if .Values.dataPlane.components.api }}
      {{- if .Values.dataPlane.components.api.trustTestConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-plane-trusttest-config
  labels:
    app: api
    plane: data
data:
  .trusttest_config.json: |-
    {{ .Values.dataPlane.components.api.trustTestConfig | toJson | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }} 