{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "common.names.fullname" . }}
{{- $namespace := .Release.Namespace }}
{{- $existingSecret := (lookup "v1" "Secret" $namespace $secretName) }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: clickhouse
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "admin-password" "providedValues" (list "auth.password") "context" $) }}
{{- end }}
{{- end }}
