{{- $p := index .Values.controlPlane.components.postgresql "persistence" }}
{{- if and (include "control-plane.postgresql.deploy" .) $p }}
{{- if index $p "enabled" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-plane-postgresql-pvc
  labels:
    app: control-plane-postgresql
  {{- if index $p "preserveOnDelete" | default true }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if index $p "storageClass" }}
  storageClassName: {{ index $p "storageClass" }}
  {{- end }}
  resources:
    requests:
      storage: {{ index $p "size" | default "10Gi" }}
{{- end }}
{{- end }} 