{{- if and (include "control-plane.postgresql.deploy" .) .Values.controlPlane.components.postgresql.persistence .Values.controlPlane.components.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-plane-postgresql-pvc
  labels:
    app: control-plane-postgresql
  {{- if and .Values.controlPlane .Values.controlPlane.components .Values.controlPlane.components.postgresql .Values.controlPlane.components.postgresql.persistence (.Values.controlPlane.components.postgresql.persistence.preserveOnDelete | default true) }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if and .Values.controlPlane .Values.controlPlane.components .Values.controlPlane.components.postgresql .Values.controlPlane.components.postgresql.persistence .Values.controlPlane.components.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.controlPlane.components.postgresql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ if and .Values.controlPlane .Values.controlPlane.components .Values.controlPlane.components.postgresql .Values.controlPlane.components.postgresql.persistence .Values.controlPlane.components.postgresql.persistence.size }}{{ .Values.controlPlane.components.postgresql.persistence.size }}{{ else }}10Gi{{ end }}
{{- end }} 