apiVersion: v1
kind: Service
metadata:
  name: "data-plane-api-service"
  labels:
    app: api
spec:
  type: {{ if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.service }}{{ .Values.dataPlane.components.api.service.type | default "LoadBalancer" }}{{ else }}LoadBalancer{{ end }}
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: api
{{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "data-plane-api-ingress"
  {{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.annotations }}
  annotations:
    {{- toYaml .Values.dataPlane.components.api.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.className }}
  ingressClassName: {{ .Values.dataPlane.components.api.ingress.className }}
  {{- end }}
  {{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.tls .Values.dataPlane.components.api.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.dataPlane.components.api.host }}"
      {{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.tls .Values.dataPlane.components.api.ingress.tls.secretName }}
      secretName: {{ .Values.dataPlane.components.api.ingress.tls.secretName }}
      {{- else }}
      secretName: "data-plane-api-tls"
      {{- end }}
  {{- end }}
  rules:
    - host: "{{ if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api }}{{ .Values.dataPlane.components.api.host }}{{ else }}data-plane-api.neuraltrust.ai{{ end }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "data-plane-api-service"
                port:
                  name: http
{{- end }}
{{- if and .Values.global.openshift (not (and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.enabled)) }}
  {{- $host := "" }}
  {{- if .Values.global.openshiftDomain }}
    {{- $host = printf "data-plane-api.%s" .Values.global.openshiftDomain }}
  {{- else if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.host }}
    {{- $host = .Values.dataPlane.components.api.host }}
  {{- else }}
    {{- $host = "data-plane-api.neuraltrust.ai" }}
  {{- end }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "data-plane-api-route"
spec:
  host: {{ $host | quote }}
  tls:
    {{- $tlsConfig := dict }}
    {{- if and .Values.dataPlane .Values.dataPlane.components .Values.dataPlane.components.api .Values.dataPlane.components.api.ingress .Values.dataPlane.components.api.ingress.tls }}
      {{- $tlsConfig = .Values.dataPlane.components.api.ingress.tls }}
    {{- end }}
    {{- $tlsSecretName := "" }}
    {{- $certFromSecret := "" }}
    {{- $keyFromSecret := "" }}
    {{- if $tlsConfig.secretName }}
      {{- $tlsSecretName = $tlsConfig.secretName }}
      {{- $tlsSecret := (lookup "v1" "Secret" .Release.Namespace $tlsSecretName) }}
      {{- if $tlsSecret }}
        {{- if hasKey $tlsSecret.data "tls.crt" }}
          {{- $certFromSecret = index $tlsSecret.data "tls.crt" | b64dec }}
        {{- end }}
        {{- if hasKey $tlsSecret.data "tls.key" }}
          {{- $keyFromSecret = index $tlsSecret.data "tls.key" | b64dec }}
        {{- end }}
      {{- end }}
    {{- end }}
    termination: {{ if $tlsConfig.termination }}{{ $tlsConfig.termination }}{{ else }}edge{{ end }}
    {{- if $certFromSecret }}
    certificate: {{ $certFromSecret | quote }}
    {{- else if $tlsConfig.certificate }}
    certificate: {{ $tlsConfig.certificate | quote }}
    {{- end }}
    {{- if $keyFromSecret }}
    key: {{ $keyFromSecret | quote }}
    {{- else if $tlsConfig.key }}
    key: {{ $tlsConfig.key | quote }}
    {{- end }}
    {{- if $tlsConfig.caCertificate }}
    caCertificate: {{ $tlsConfig.caCertificate | quote }}
    {{- end }}
    {{- if $tlsConfig.destinationCACertificate }}
    destinationCACertificate: {{ $tlsConfig.destinationCACertificate | quote }}
    {{- end }}
    insecureEdgeTerminationPolicy: {{ if $tlsConfig.insecureEdgeTerminationPolicy }}{{ $tlsConfig.insecureEdgeTerminationPolicy }}{{ else }}Redirect{{ end }}
  to:
    kind: Service
    name: "data-plane-api-service"
    weight: 100
  port:
    targetPort: http
  path: "/"
{{- end }}